# Generated by Django 3.2.5 on 2022-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('datum_osnivanja', models.DateField()),
                ('lozinka', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('lozinka', models.CharField(max_length=20)),
            ],
        ),
    ]
