# Generated by Django 3.2.5 on 2022-06-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_i_registracija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahtjevi_Putovanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_mjesta', models.CharField(max_length=150)),
                ('datum', models.DateField()),
                ('ponuda_cijena', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('agencija_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_i_registracija.agencije')),
                ('korisnik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_i_registracija.korisnici')),
            ],
        ),
        migrations.CreateModel(
            name='Putovanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_broj_putnika', models.IntegerField()),
                ('max_broj_putnika', models.IntegerField()),
                ('naziv_mjesta', models.CharField(max_length=150)),
                ('latituda', models.FloatField()),
                ('longituda', models.FloatField()),
                ('datum', models.DateField()),
                ('tip', models.CharField(max_length=100)),
                ('vrsta_prevoza', models.CharField(max_length=300)),
                ('cijena', models.FloatField()),
                ('agencija_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_i_registracija.agencije')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik_Putovanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_i_registracija.korisnici')),
                ('putovanje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_i_registracija.putovanja')),
            ],
        ),
    ]
