# Generated by Django 3.2.5 on 2022-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_i_registracija', '0004_auto_20220605_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='putovanja',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
