# Generated by Django 3.2.5 on 2022-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_i_registracija', '0008_auto_20220608_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putovanja',
            name='latituda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='putovanja',
            name='longituda',
            field=models.FloatField(null=True),
        ),
    ]
